radarr:
  url: "${RADARR_URL}"
  api_key: "${RADARR_API_KEY}"

plex:
  url: "${PLEX_URL}"
  token: "${PLEX_TOKEN}"

language_filter: ${LANGUAGE_FILTER:-false}  # Use default value `false` if not specified
accepted_languages: ${ACCEPTED_LANGUAGES"}  # Comma-separated list

movie_collection_name: "${MOVIE_COLLECTION_NAME}"
log_directory: "${LOG_DIRECTORY:-/app/logs}"  # Default to `/app/logs` if not set