services:  
  radarr_autodelete:
    image: iedgir01/radarr_autodelete:latest
    container_name: radarr_autodelete
    networks:
      - media_server
    volumes:
      - '/docker/radarr_autodelete/logs:/app/logs'
      - '/docker/radarr_autodelete/config:/app/config'
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Africa/Johannesburg
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
networks:
  media_server:
    external: true