services:  
  radarr_autodelete:
    image: iedgir01/radarr_autodelete:latest
    container_name: radarr_autodelete
    networks:
      - media_server
    volumes:
      - '/path/to/your/radarr_autodelete/logs:/app/logs'
    environment:
      #LOGIN FOR PLEX - ALLOWS FOR WATCH HISTORY FILTERING TO THIS SPECIFIC USER
      - PLEX_USERNAME=your_plex_username
      - PLEX_PASSWORD=your_plex_password
      - PLEX_URL=http://your_plex_url:port
      - PLEX_TOKEN=your_plex_token

      #LOGIN FOR RADARR
      - RADARR_URL=http://your_radarr_url:port
      - RADARR_API_KEY=your_radarr_api

      #Language filtering and collection name
      - LANGUAGE_FILTER=true #true/false for language filtering
      - ACCEPTED_LANGUAGES=English,Japanese,Korean 
      - MOVIE_COLLECTION_NAME=Your_PLex_Collection_To_Keep

      #Other settings
      - DRY_RUN=true #true/false for testing
      - PUID=1000 #Change to your PUID
      - PGID=1000 #Change to your PGID
      - TZ=UTC #Change to your TZ
        
networks:
  media_server:
    external: true
